% Ingredient facts
Ingredient(almonds).
Ingredient(apricot).
Ingredient(avocado).
Ingredient(banana).
Ingredient(beans).
Ingredient(beef).
Ingredient(bison).
Ingredient(blueberry).
Ingredient(broccoli).
Ingredient(butter).
Ingredient(chicken).
Ingredient(egg).
Ingredient(eggplant).
Ingredient(flour).
Ingredient(garlic).
Ingredient(kale).
Ingredient(kiwi).
Ingredient(lentils).
Ingredient(melon).
Ingredient(milk).
Ingredient(mozzarella).
Ingredient(mushroom).
Ingredient(olive_oil).
Ingredient(onion).
Ingredient(parmesan_cheese).
Ingredient(pasta).
Ingredient(peach).
Ingredient(pecans).
Ingredient(pine_nuts).
Ingredient(pork).
Ingredient(ricotta).
Ingredient(salmon).
Ingredient(salt).
Ingredient(snapper).
Ingredient(spinach).
Ingredient(sugar).
Ingredient(swordfish).
Ingredient(tomato).
Ingredient(tuna).
Ingredient(walnuts).
Ingredient(yogurt).
Ingredient(zucchini).
