% ALLERGEN FACTS (Top 9). Only tagged ingredients; rest untagged.
% HasAllergen(ingredient, allergen).
%
HasAllergen(almonds, tree_nuts).
HasAllergen(anchovy_fillet, fish).
HasAllergen(anchovy_fillet_std, fish).
HasAllergen(bowtie_pasta, wheat).
HasAllergen(bread, wheat).
HasAllergen(bread_white_std, wheat).
HasAllergen(butter, milk).
HasAllergen(creme_fraiche, milk).
HasAllergen(creme_fraiche_std, milk).
HasAllergen(dry_pasta, wheat).
HasAllergen(egg, egg).
HasAllergen(egg_yolks, egg).
HasAllergen(egg_yolks_std, egg).
HasAllergen(eggplant, egg).
HasAllergen(farfalle, wheat).
HasAllergen(flour, wheat).
HasAllergen(fromage_frais, milk).
HasAllergen(fromage_frais_std, milk).
HasAllergen(king_prawns, shellfish).
HasAllergen(king_prawns_std, shellfish).
HasAllergen(lasagna_noodles, wheat).
HasAllergen(linguine_pasta, wheat).
HasAllergen(mascarpone, milk).
HasAllergen(mascarpone_std, milk).
HasAllergen(milk, milk).
HasAllergen(mozzarella, milk).
HasAllergen(mozzarella_balls, milk).
HasAllergen(mozzarella_balls_std, milk).
HasAllergen(paccheri_pasta, wheat).
HasAllergen(parmesan_cheese, milk).
HasAllergen(parmigiano_reggiano, milk).
HasAllergen(parmigiano_reggiano, egg).
HasAllergen(parmigiano_reggiano_std, milk).
HasAllergen(parmigiano_reggiano_std, egg).
HasAllergen(pasta, wheat).
HasAllergen(pecans, tree_nuts).
HasAllergen(pecorino, milk).
HasAllergen(pecorino_cheese, milk).
HasAllergen(pecorino_std, milk).
HasAllergen(penne, wheat).
HasAllergen(pilchards, fish).
HasAllergen(pilchards_std, fish).
HasAllergen(pine_nuts, tree_nuts).
HasAllergen(ricotta, milk).
HasAllergen(rigatoni, wheat).
HasAllergen(salmon, fish).
HasAllergen(snapper, fish).
HasAllergen(soy_milk, milk).
HasAllergen(soy_milk, soy).
HasAllergen(soy_milk_std, milk).
HasAllergen(soy_milk_std, soy).
HasAllergen(spaghetti, wheat).
HasAllergen(swordfish, fish).
HasAllergen(tuna, fish).
HasAllergen(vegan_butter, milk).
HasAllergen(vegan_butter_std, milk).
HasAllergen(walnuts, tree_nuts).
HasAllergen(wholegrain_bread, wheat).
HasAllergen(wholegrain_bread_std, wheat).
HasAllergen(yogurt, milk).
